server:
  port: 8000
  servlet:
    context-path: /demo

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Exper5zdm/
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/** # 作用是访问静态文件，必须加上static
  devtools:
    restart:
      enabled: true #设置开启热部署

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml # mapper位置
  type-aliases-package: com.sys.model,;com.sys.vo, # mapper.xml文件里直接写类名,配置多个用,;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0
  params: count=countSql

#showSql
logging:
  level:
    com:
      example:
        mapper : debug